### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by MaheshCapcee** [kunmi/BlogTutorials#1]
how to remove tittle bar space

**Comment by kunmi** [comment]
Can you share a screenshot or explain better?
If it's what I think, you should attach a style to your dialogfragment through this in the onCreate of the dialogfragment.

`setStyle(DialogFragment.STYLE_NORMAL, R.style.DIAGSTYLE); `

In your styles, set WindowNoTitle to false:
```
    <style name="MyDialogFragmentStyle" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowActionBar">false</item>
        <item name="android:windowNoTitle">true</item>
    </style>

```
