### ISSUE TITLE
How to Add MarginBottom & Show Title ?

### ISSUE THREAD

**Issue by exzant** [kunmi/BlogTutorials#2]
Please see this image
http://oi64.tinypic.com/33e790g.jpg

How to Add MarginBottom & Show Title ?
How to dismiss when click grey area outside ?

**Comment by kunmi** [comment]
Hi,

-> **For Click in the grey area:**
To enable this behaviour for dismissal when the background is clicked, call `setCancelable(true)` on your dialog-fragment object or dialog-builder object. if you are making use of AlertDialog, then you should call `setCanceledOnTouchOutside(true)`.

Although, as far as I know, this behaviour is enabled by default. From the image you uploaded, your dialog is very WIDE!!!! the immediate space still belongs to the dialog's window, the background that responds to touch is some pixels away from the dialog's box. **Rotate** that emulator to landscape, I bet it'll work!

**-> Show title:**
This can be done in two ways, you have a custom layout there and can simply add a textview, but if you want to use the default system **dialog title**, complete with system **Positive** and **Negative Buttons**. I made a gist here showing how to achieve that: [https://gist.github.com/kunmi/7a5ce2a4780e9107ebaadf8d9bd72dcb](https://gist.github.com/kunmi/7a5ce2a4780e9107ebaadf8d9bd72dcb)

**-> MarginBottom:**
do you mean bottom-margin between the dialog and the bottom of the screen, or between views? if it is between views, you have access to the layout XML of the custom view, you can mod it as you please.

PS: it's almost  5:00 am-midnight / morning!!!! Sleepy much, I'll def. wake up late. I'll read your reply when I'm up. 

Nice Weekend, I hope this helps.

**Comment by sojujs** [comment]
hey kunmi,

I wanted to know if its possible to change the vertical size of the whole dialog ?
Like right now it is being stretched horizontally from the top of the screen towards the bottom. I required it placed in the center as a square of sorts.

Thanks in advance !

**Comment by kunmi** [comment]
Hi!

You can fix this by assigning a fixed height in your layout; For example, if you are using a viewpager (as is in the sample tutorial), change the viewpager's height to 50dp or any other suitable size.

**Comment by exzant** [comment]
Hi Kunmi,

I've tried to add MarginBottom into Layout either ViewPager,
but it's still FullScreen
http://oi63.tinypic.com/os72xe.jpg
How to make it 50dp above bottom screen ?

Thank You

**Comment by sojujs** [comment]
Hey,

Thanks kunmi for the reply, although i found another workaround for the same.

@exzant you can try doing this to your DialogFragment file:-

The onresume method should look like this

@Override
    public void onResume() {
        super.onResume();
        int width = getResources().getDimensionPixelSize(R.dimen.popup_width);
        int height = getResources().getDimensionPixelSize(R.dimen.popup_height);
        Objects.requireNonNull(getDialog().getWindow()).setLayout(width, height);
    }

i gave it a defined height and width, you can try experimenting with it as per your requirements.

**Comment by kunmi** [comment]
@sojujs  
Nice to see you were able to get it working. 

@exzant  
I meant the Viewpager, you should give it a fixed height, this is a sample with viewpager height set to 50dp:
[http://i66.tinypic.com/ht5k5h.jpg](http://i66.tinypic.com/ht5k5h.jpg)
 
and you can also try the suggestion from @sojujs
